@baseURL = http://localhost:8080/meals 
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzQ5Mzk5NDEsInN1YiI6Ijc5YzAxMThhLWVlOWEtNDEzYS05OTcwLWVkYTY4OGE4NjYyOSJ9.JJv0Ddr7ZxlzdlfKVjAKQs-O1WW6Pdu6rDIfMvPxZf8

### Create Meal 
POST {{baseURL}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Meal Sem ID",
  "description": "Sem o ID",
  "date": "2024-12-09T14:30:00Z",
  "is_diet": true
}

### Get all meals by user
GET {{baseURL}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### Get meals metrics by user
GET {{baseURL}}/metrics HTTP/1.1
Authorization: Bearer {{token}}

### Get meals by status
@status = false
GET {{baseURL}}/status?status={{status}} HTTP/1.1
Authorization: Bearer {{token}}

### Update meal
@meal_id = 46604385-ad36-4bd7-a18d-e86cd513fae1
PUT {{baseURL}}/{{meal_id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Confirmação Alt",
  "description": "Alt Alt",
  "date": "2024-12-09T14:30:00Z",
  "is_diet": false
}

### Delete meal
@meal_id = 46604385-ad36-4bd7-a18d-e86cd513fae1
DELETE  {{baseURL}}/{{meal_id}} HTTP/1.1
Authorization: Bearer {{token}}
