@baseURL = http://localhost:8080
@id = 7be8c10e-91e3-48da-aed6-b61eb4615ba2

PUT {{baseURL}}/meals/{{id}} HTTP/1.1
Content-Type: application/json

{
  "name": "Confirmação Alt",
  "description": "Alt Alt",
  "date": "2024-12-09T14:30:00Z",
  "is_diet": false
}